# Generated by Django 5.1.1 on 2024-09-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=240),
        ),
    ]
