# Generated by Django 5.0.1 on 2024-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.IntegerField(),
        ),
    ]
